# -*- coding: utf-8 -*-
"""ingesta_pkm.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GgNSfaZlAe9rbFSpTmNY-7gAkZsZo4E

Creacion Carpetas
"""

import os

carpetas = [
    "proyecto_ingesta/data/raw",
    "proyecto_ingesta/data/control"
]

for carpeta in carpetas:
    os.makedirs(carpeta, exist_ok=True)
    print(f"Carpeta creada: {carpeta}")

"""Script de ingesta de datos incremental"""

import requests
import pandas as pd
import os
import json

# Configuración
RAW_DIR      = "proyecto_ingesta/data/raw"
CONTROL_FILE = "proyecto_ingesta/data/control/control.json"
BASE_URL     = "https://pokeapi.co/api/v2/pokemon"

#C incremental
def cargar_control():
    if os.path.exists(CONTROL_FILE):
        with open(CONTROL_FILE, "r") as f:
            return json.load(f)
    return {"lotes_procesados": []}

def guardar_control(control):
    os.makedirs(os.path.dirname(CONTROL_FILE), exist_ok=True)
    with open(CONTROL_FILE, "w") as f:
        json.dump(control, f, indent=2)
#Camppos
def parsear_pokemon(data: dict) -> dict:
    stats = {s["stat"]["name"]: s["base_stat"] for s in data["stats"]}
    tipos = "/".join(t["type"]["name"] for t in data["types"])

    return {
        "id":        data["id"],
        "nombre":    data["name"],
        "altura":    data["height"],
        "peso":      data["weight"],
        "tipos":     tipos,
        "hp":        stats.get("hp"),
        "ataque":    stats.get("attack"),
        "defensa":   stats.get("defense"),
        "velocidad": stats.get("speed"),
    }

#Ingesta
def ingestar_rango(id_inicio: int, id_fin: int):
    control = cargar_control()
    clave = f"ids_{id_inicio}_{id_fin}"

    registros = []
    errores = 0

    for pokemon_id in range(id_inicio, id_fin + 1):
        try:
            resp = requests.get(f"{BASE_URL}/{pokemon_id}", timeout=10)
            resp.raise_for_status()

            datos = parsear_pokemon(resp.json())
            registros.append(datos)

            print(f"#{pokemon_id} {datos['nombre']} ({datos['tipos']})")

        except requests.exceptions.HTTPError:
            print(f"ID {pokemon_id} no encontrado")
            errores += 1
        except Exception as e:
            print(f"Error en ID {pokemon_id}: {e}")
            errores += 1

    if not registros:
        print(" No se obtuvo ningún registro.")
        return

    # G CSV
    df = pd.DataFrame(registros)
    os.makedirs(RAW_DIR, exist_ok=True)

    archivo = f"{RAW_DIR}/pokemon_ids_{id_inicio}_{id_fin}.csv"
    df.to_csv(archivo, index=False)

    print(f" Guardado: {archivo}")
    print(f" {len(registros)} registros | {errores} errores")

    control["lotes_procesados"].append(clave)
    control[clave] = {
        "registros": len(registros),
        "errores": errores,
        "archivo": archivo,
        "timestamp": datetime.now().isoformat()
    }
    guardar_control(control)

from datetime import datetime

ingestar_rango(1, 20)
df = pd.read_csv("proyecto_ingesta/data/raw/pokemon_ids_1_20.csv")
print(df.head(10))

"""estructrura :



proyecto_ingesta/
├── data/
│   ├── raw/
│   │   ├── pokemon_ids_1_20.csv
│   │   └── pokemon_ids_21_40.csv
│   └── control/
│       └── control.json
├── ingesta.py
└── README.md
"""